version: "3"
services:

  mysql:
    image: mysql:5.7.18
    ports:
      - "3306:3306"
    volumes:
      - ./db_data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin111
    restart: always

  redis:
    image: redis:latest
    ports:
      - "32768:6379"
    volumes:
      - ./db_data/redis/:/var/lib/redis/
    restart: always

  backend:
    build: backend/
    ports:
      - "8086:8086"
      - "8084:8084"
    depends_on:
      - mysql
      - redis
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        java -jar /app/avm.jar
        java -jar /app/avr.jar

  fronted:
    build: fronted/
    ports:
      - "8088:80"
    volumes:
      - ./web:/www/web/
      - ./log/nginx:/var/log/nginx
    depends_on:
      - backend
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        echo "init ok!!!"