version: "3"
services:

  mysql:
    image: mysql:5.7.18
    ports:
      - "3306:3306"
    volumes:
      - ./db_data/mysql:/var/lib/mysql
      - ./log/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: admin111
    restart: always

  redis:
    image: redis:latest
    ports:
      - "32768:6379"
    volumes:
      - ./db_data/redis/:/var/lib/redis/
    restart: always

  backend:
    image: java:8
    ports:
      - "8086:8086"
      - "8084:8084"
    depends_on:
      - mysql
      - redis
    restart: always
    volumes:
      - "/app"
    command:
      - /bin/sh
      - -c
      - |
        java -jar /app/avm.jar
        java -jar /app/avr.jar

  fronted:
    image: nginx
    ports:
      - "8088:80"
    volumes:
      - ./fronted/dist:/usr/share/nginx/html
      - ./fronted/fronted.conf:/etc/nginx/conf.d/fronted.conf
    depends_on:
      - backend
    restart: always